### ISSUE TITLE
OnTap?

### ISSUE THREAD

**Issue by Benvanj** [BenjaminMahmic/collasable_drawer#1]
Hi thank you for an amazing menu. How would I implement on onTap in the menu, I would like to specify, an onTap in expanded view and collapsed views?

**Comment by BenjaminMahmic** [comment]
In this, that is, the current version, the plan was just to present this as an UI, as this is of great interest, I think I will make a special package for pub.dev where everything will be possible to adjust manually .. and with many more options than the current

**Comment by evanrich** [comment]
Did you ever get a package created @BenjaminMahmic ?  interested in this as well.

**Comment by BenjaminMahmic** [comment]
Unfortunately, I am limited with time, but I plan to do it.
