### ISSUE TITLE
List item text seems to "rubberband" back once list is open

### ISSUE THREAD

**Issue by evanrich** [BenjaminMahmic/collasable_drawer#2]
First of all, thank you for an amazing bit of code.  The drawer looks amazing.  I tried running this in my browser (chrome) and the list text seems to "spring" or "rubberband" back a little when transitioning from closed to open.  I did increase the font size a bit but I dont think it's that.  Do you know why this might be?

I was looking to learn flutter by implementing something like this and this is a huge help for me getting started.

**Comment by BenjaminMahmic** [comment]
I made this quite a long time ago.. try to make some corrections if you want to get a different result.. On a mobile device (what it is intended for) everything works solidly.
